# Generated by Django 4.2.7 on 2023-12-10 07:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(choices=[('Ibuprofen', 'Ibuprofen'), ('Paracetamol', 'Paracetamol'), ('Zyrtec', 'Zyrtec'), ('Cetirizine', 'Cetirizine'), ('Promethazine', 'Promethazine'), ('Ivy Leaf Extract', 'Ivy Leaf Extract')], max_length=50)),
                ('rec_interval', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('used_for', models.TextField(default='', max_length=500)),
                ('sideeffects', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField(default=4)),
                ('last_fed', models.DateTimeField(default=datetime.datetime.now)),
                ('second_dose', models.DateTimeField(default=None, null=True)),
                ('third_dose', models.DateTimeField(default=None, null=True)),
                ('fourth_dose', models.DateTimeField(default=None, null=True)),
                ('fifth_dose', models.DateTimeField(default=None, null=True)),
                ('remarks', models.TextField(blank=True, max_length=140)),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trackerapp.medicalinfo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['complete'],
            },
        ),
    ]
