# Generated by Django 4.2.7 on 2023-11-17 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatmodel',
            name='last_fed',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 19, 57, 15, 80278)),
        ),
        migrations.AlterField(
            model_name='eatmodel',
            name='medicine',
            field=models.CharField(choices=[('ibuprofen', 'Ibuprofen'), ('paracetamol', 'Paracetamol'), ('zyrtec', 'Zyrtec'), ('cetirizine', 'Cetirizine'), ('promethazine', 'Promethazine'), ('ivy', 'Ivy Leaf Extract')], max_length=50),
        ),
    ]
