# Generated by Django 4.2.7 on 2023-11-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatmodel',
            name='fourth_dose',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='eatmodel',
            name='second_dose',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='eatmodel',
            name='third_dose',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
