# Generated by Django 4.2.7 on 2023-11-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0002_alter_eatmodel_fourth_dose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatmodel',
            name='fifth_dose',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
