# Generated by Django 4.2.7 on 2023-11-17 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0003_alter_eatmodel_last_fed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatmodel',
            name='last_fed',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='eatmodel',
            name='remarks',
            field=models.TextField(max_length=140),
        ),
    ]
