# Generated by Django 4.2.7 on 2023-12-10 08:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0003_eatmodel_fifth_dose'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_timing', models.DateTimeField(default=datetime.datetime.now)),
                ('dose_complete', models.BooleanField(default=False, null=True)),
                ('eatmodel', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='trackerapp.eatmodel')),
            ],
        ),
    ]
