# Generated by Django 4.2.7 on 2023-11-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0004_alter_eatmodel_last_fed_alter_eatmodel_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(choices=[('Ibuprofen', 'Ibuprofen'), ('Paracetamol', 'Paracetamol'), ('Zyrtec', 'Zyrtec'), ('Cetirizine', 'Cetirizine'), ('Promethazine', 'Promethazine'), ('Ivy Leaf Extract', 'Ivy Leaf Extract')], max_length=50)),
                ('rec_interval', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('sideeffects', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='eatmodel',
            name='interval',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='eatmodel',
            name='medicine',
            field=models.CharField(choices=[('Ibuprofen', 'Ibuprofen'), ('Paracetamol', 'Paracetamol'), ('Zyrtec', 'Zyrtec'), ('Cetirizine', 'Cetirizine'), ('Promethazine', 'Promethazine'), ('Ivy Leaf Extract', 'Ivy Leaf Extract')], max_length=50),
        ),
    ]
