# Generated by Django 4.2.7 on 2023-11-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0005_medicalinfo_eatmodel_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalinfo',
            name='used_for',
            field=models.TextField(default='', max_length=500),
        ),
    ]
