# Generated by Django 4.2.7 on 2023-12-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0005_rename_eatmodel_dosesinfo_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosesinfo',
            old_name='course',
            new_name='eatmodel',
        ),
    ]
