# Generated by Django 4.2.7 on 2023-11-22 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0006_medicalinfo_used_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatmodel',
            name='medicine_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trackerapp.medicalinfo'),
        ),
    ]
