# Generated by Django 4.2.7 on 2023-12-10 10:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trackerapp', '0006_rename_course_dosesinfo_eatmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField(default=4)),
                ('course_duration', models.IntegerField(default=3)),
                ('start_dose', models.DateTimeField(default=datetime.datetime.now)),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trackerapp.medicalinfo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_timing', models.DateTimeField(default=datetime.datetime.now)),
                ('dose_complete', models.BooleanField(default=False, null=True)),
                ('courseinfo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='trackerapp.courseinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='DosesInfo',
        ),
    ]
