# Generated by Django 4.2.7 on 2023-11-22 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0007_eatmodel_medicine_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eatmodel',
            name='medicine_pk',
        ),
        migrations.AlterField(
            model_name='eatmodel',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trackerapp.medicalinfo'),
        ),
    ]
