# Generated by Django 4.2.7 on 2023-12-10 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0007_courseinfo_doseinfo_delete_dosesinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinfo',
            old_name='created',
            new_name='course_created',
        ),
        migrations.RemoveField(
            model_name='doseinfo',
            name='dose_complete',
        ),
        migrations.AddField(
            model_name='doseinfo',
            name='dose_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
