# Generated by Django 4.2.7 on 2023-12-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0008_rename_created_courseinfo_course_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinfo',
            old_name='start_dose',
            new_name='course_start',
        ),
    ]
