# Generated by Django 4.2.7 on 2023-12-14 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0010_medicalinfo_brandnames_alter_courseinfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalinfo',
            old_name='brandnames',
            new_name='brandname',
        ),
    ]
