# Generated by Django 4.2.7 on 2023-12-16 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0011_rename_brandnames_medicalinfo_brandname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='doseinfo',
            options={'ordering': ['dose_timing']},
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trackerapp.patient'),
        ),
    ]
